
   
   <div id=drop-menu> <!-- Sammensat kode til drop down menu-->
            <ul>
                <li>
            <button class="openbtn" onclick="openNav()"> <img src="Billeder/burger-menu-icon.png" width="50px" ></button>
                
                <ul>
                    <li><a href="Forside.php"> Forside </a></li>
                    <li> <a href="Server.php"> Server </a> </li>
                    <li> <a href="Website.php"> Website </a> </li>
                    
                    <li> <a href="Informationsarkitektur.php"> Informationsarkitektur </a> </li>
                    
                    <li> <a href="Kommunikation.php">Kommunikation </a> </li>
                    
                    <li><a href="Tekst.php">Tekst </a> </li>
                    
                    <li><a href="Kvantitativ.php">Brugertest </a> </li>
                    
                    <li><a href="Business.php">Business</a> </li>
                    
                    <li><a href="Illustrationer.php">Illustrationer </a></li>
                    
                    <li><a href="Design thinking.php">Design thinking</a> </li>
                    
                    <li><a href="OnePageProjekt.php">OnePageProjekt </a> </li>
                    
                    <li><a href="EksamenProjekt.php">Eksamen Projekt</a> </li>
                    
                    <li><a href="Kilder.php">Kilder</a> </li>
        
                </ul>
                </li>
            
            </ul>
            
        </div>
        
    